language: node_js
sudo: required
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
node_js:
  - 4
  - 6
  - node
script:
  - npm test
  - make test-cov
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: eirik@morland.no
  api_key:
    secure: JGMolB+ag64E4y4YssquE92F7A+JrrbOmLYT4rcd/r3738+BZ/S+sPLJEBwOff24H5+siLs45AorMNsifjRtaWNvqK2Hpnq7gAH6m7vnBAS2YpRn8OxHjZOA3zAgVNln6p45euCHhmhPVS+ORhrNClMCMRGoXtRbkO6YdFCX3Mo=
  on:
    tags: true
    repo: eiriksm/commit-a-day
